name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --dev
        env:
          PATH: ${{ runner.workspace }}/.bun/bin:$PATH
      - name: Run build with Bun
        run: bun run build
        env:
          PATH: ${{ runner.workspace }}/.bun/bin:$PATH
